name: Create Release

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: "Publish with Gradle in Repository"
        uses: gradle/gradle-build-action@v3
        env:
          REPO_USERNAME: ${{ secrets.KALIMERO2_REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.KALIMERO2_REPO_SECRET }}
        with:
          arguments: build publish
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "**/dclink-*/build/libs/*.jar"
